// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoodTracker_MVC.Models;

public partial class Mood
{
    public int MoodId { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

//    public virtual ICollection<UserMood> UserMoods { get; set; } = new List<UserMood>();
}