// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoodTracker_MVC.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsAdmin { get; set; }

    public virtual ICollection<UserLogin> UserLogins { get; set; } = new List<UserLogin>();
}