// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoodTracker_MVC.Models;

public partial class UserLogin
{
    public int LoginId { get; set; }

    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}